#!/bin/bash
pip install oerplib
pip install argparse
pip install argcomplete
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"  )" && pwd  )"
echo "alias odoo-i18n-export='python ${DIR}/odoo-i18n-export.py'" >> ${HOME}/.profile
source ${HOME}/.profile
